server:
  port: 20008
  ip: 0.0.0.0

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation: TRACE

spring:
  application:
    name: "druid-monitor"
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/order_service?useUnicode=true&useSSL=false
      username: root
      password: 123
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      pool-prepared-statements: true
      filters: mergeStat,wall
    monitor:
      login:
        username: admin
        password: 123456
